from metodos.newton_hacia_adelante import Newton_hacia_adelante
from metodos.interpolacion_lineal import Interpolacion_lineal
from metodos.newton_hacia_atras import Newton_hacia_atras
from metodos.lagrange import Lagrange
from metodos.newton_diferencias_divididas import Newton_Diferencias_Divididas

from metodos.punto_fijo import Punto_Fijo
from metodos.metodo_bisectriz import Bisectriz
from metodos.raphson import Newton_Raphson
from metodos.secante import Secante


from metodos.gauss_jordan import GaussJordan

from metodos.integracion_trapezoidal import Integracion_trapezoidal
from metodos.integracion_simson13 import Integracion_simpson13
from metodos.integracion_simson38 import Integracion_simpson38
from metodos.integracion_coteCerrada import Integracion_cotasCerrada
from metodos.integracion_coteAbierta import Integracion_cotasAbiertas
