from metodos.newton_hacia_adelante import Newton_hacia_adelante

from metodos.interpolacion_lineal import Interpolacion_lineal

from metodos.newton_hacia_atras import Newton_hacia_atras
from metodos.lagrange import Lagrange
from metodos.punto_fijo import PuntoFijo

from metodos.integracion_trapezoidal import Integracion_trapezoidal
from metodos.integracion_simson13 import Integracion_simpson13
from metodos.integracion_simson38 import Integracion_simpson38
from metodos.integracion_coteCerrada import Integracion_cotasCerrada
